#!/usr/bin/env sh
set -e

# Runtime environment variable injection
cat > /app/dist/env-config.js << EOF
window._env_ = {
  VITE_SUPABASE_URL: "${VITE_SUPABASE_URL}",
  VITE_SUPABASE_ANON_KEY: "${VITE_SUPABASE_ANON_KEY}",
  VITE_SUPABASE_PUBLISHABLE_KEY: "${VITE_SUPABASE_PUBLISHABLE_KEY:-${VITE_SUPABASE_ANON_KEY}}",
  VITE_AISHACRM_BACKEND_URL: "${VITE_AISHACRM_BACKEND_URL}",
  VITE_CURRENT_BRANCH: "${VITE_CURRENT_BRANCH:-main}",
  VITE_SYSTEM_TENANT_ID: "${VITE_SYSTEM_TENANT_ID}",
  VITE_USER_HEARTBEAT_INTERVAL_MS: "${VITE_USER_HEARTBEAT_INTERVAL_MS:-90000}"
  , APP_BUILD_VERSION: "${APP_BUILD_VERSION:-dev-local}"
};
EOF

: "${PORT:=3000}"

# Start static server
exec sh -c "serve -s dist -l ${PORT}"
