/**
 * User Role Templates
 * Pre-configured permission and team settings for common user roles
 * Used by User Management wizard to speed up user creation
 */

export const USER_ROLE_TEMPLATES = {
  'employee-limited': {
    name: 'Employee (Limited)',
    description: 'Own records R/W, other records read-only with notes',
    emoji: '👤',
    role: 'employee',
    permissions: {
      perm_notes_anywhere: true,
      perm_all_records: false,
      perm_reports: false,
      perm_employees: false,
      perm_settings: false,
    },
    teamAccessLevel: 'view_own',
    navModules: [
      'Dashboard',
      'Contacts',
      'Accounts',
      'Leads',
      'Opportunities',
      'Activities',
      'Calendar',
      'BizDevSources',
      'CashFlow',
      'DocumentProcessing',
      'DocumentManagement',
      'AICampaigns',
      'PaymentPortal',
      'Documentation',
    ],
  },
  'employee-full': {
    name: 'Employee (Full Access)',
    description: 'View and update any record in the organization',
    emoji: '💼',
    role: 'employee',
    permissions: {
      perm_notes_anywhere: false,
      perm_all_records: true,
      perm_reports: false,
      perm_employees: false,
      perm_settings: false,
    },
    teamAccessLevel: 'manage_team',
    navModules: [
      'Dashboard',
      'Contacts',
      'Accounts',
      'Leads',
      'Opportunities',
      'Activities',
      'Calendar',
      'BizDevSources',
      'CashFlow',
      'DocumentProcessing',
      'DocumentManagement',
      'AICampaigns',
      'PaymentPortal',
      'Documentation',
    ],
  },
  manager: {
    name: 'Manager',
    description: 'Manage team records, view reports',
    emoji: '👨‍💼',
    role: 'manager',
    permissions: {
      perm_notes_anywhere: true,
      perm_all_records: false,
      perm_reports: true,
      perm_employees: false,
      perm_settings: false,
    },
    teamAccessLevel: 'manage_team',
    navModules: [
      'Dashboard',
      'Contacts',
      'Accounts',
      'Leads',
      'Opportunities',
      'Activities',
      'Calendar',
      'BizDevSources',
      'CashFlow',
      'DocumentProcessing',
      'DocumentManagement',
      'AICampaigns',
      'PaymentPortal',
      'Documentation',
      'Reports',
    ],
  },
  director: {
    name: 'Director',
    description: 'Full access to all records, manage multiple teams',
    emoji: '👔',
    role: 'director',
    permissions: {
      perm_notes_anywhere: false,
      perm_all_records: true,
      perm_reports: true,
      perm_employees: false,
      perm_settings: false,
    },
    teamAccessLevel: 'manage_team',
    navModules: [
      'Dashboard',
      'Contacts',
      'Accounts',
      'Leads',
      'Opportunities',
      'Activities',
      'Calendar',
      'BizDevSources',
      'CashFlow',
      'DocumentProcessing',
      'DocumentManagement',
      'AICampaigns',
      'PaymentPortal',
      'Documentation',
      'Reports',
      'Workflows',
      'Integrations',
    ],
  },
  admin: {
    name: 'Admin',
    description: 'Full access, manage settings and users',
    emoji: '🔐',
    role: 'admin',
    permissions: {
      perm_notes_anywhere: true,
      perm_all_records: true,
      perm_reports: true,
      perm_employees: true,
      perm_settings: true,
    },
    teamAccessLevel: 'manage_team',
    navModules: [
      'Dashboard',
      'Contacts',
      'Accounts',
      'Leads',
      'Opportunities',
      'Activities',
      'Calendar',
      'BizDevSources',
      'CashFlow',
      'DocumentProcessing',
      'DocumentManagement',
      'AICampaigns',
      'PaymentPortal',
      'Documentation',
      'Reports',
      'Employees',
      'Workflows',
      'Integrations',
      'Settings',
      'Utilities',
      'ClientOnboarding',
      'DeveloperAI',
      'ClientRequirements',
    ],
  },
  superadmin: {
    name: 'Superadmin',
    description: 'Complete system access across all tenants',
    emoji: '⭐',
    role: 'superadmin',
    permissions: {
      perm_notes_anywhere: true,
      perm_all_records: true,
      perm_reports: true,
      perm_employees: true,
      perm_settings: true,
    },
    teamAccessLevel: 'manage_team',
    navModules: [
      'Dashboard',
      'Contacts',
      'Accounts',
      'Leads',
      'Opportunities',
      'Activities',
      'Calendar',
      'BizDevSources',
      'CashFlow',
      'DocumentProcessing',
      'DocumentManagement',
      'AICampaigns',
      'PaymentPortal',
      'Documentation',
      'Reports',
      'Employees',
      'Workflows',
      'Integrations',
      'Settings',
      'Utilities',
      'ClientOnboarding',
      'DeveloperAI',
      'ClientRequirements',
      'ConstructionProjects',
      'Workers',
    ],
  },
};

/**
 * Get template by ID
 */
export const getTemplate = (templateId) => {
  return USER_ROLE_TEMPLATES[templateId] || null;
};

/**
 * Get all available templates for selection
 * Ordered by common usage
 */
export const getAvailableTemplates = () => {
  return [
    { id: 'employee-limited', ...USER_ROLE_TEMPLATES['employee-limited'] },
    { id: 'employee-full', ...USER_ROLE_TEMPLATES['employee-full'] },
    { id: 'manager', ...USER_ROLE_TEMPLATES['manager'] },
    { id: 'director', ...USER_ROLE_TEMPLATES['director'] },
    { id: 'admin', ...USER_ROLE_TEMPLATES['admin'] },
    { id: 'superadmin', ...USER_ROLE_TEMPLATES['superadmin'] },
  ];
};
