#cloud-config
# Cloud-init to bootstrap an Ubuntu 22.04 server for Aisha CRM backend
# - Creates a user 'aisha' (change as needed)
# - Installs Node 22, nginx, git
# - Clones repo into /home/aisha/aishacrm
# - Places a placeholder .env (you must edit with real secrets)
# - Installs npm deps, runs migrations and seed, enables systemd unit

users:
  - name: aisha
    gecos: Aisha App User
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash
    lock_passwd: false
    passwd: $6$rounds=4096$XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    ssh_authorized_keys: []

package_update: true
package_upgrade: true
packages:
  - curl
  - git
  - nginx
  - build-essential
  - ca-certificates
  - ufw

runcmd:
  # Install Node 22 via NodeSource
  - curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
  - apt-get install -y nodejs

  # Create app directory and set ownership
  - mkdir -p /home/aisha/aishacrm
  - chown aisha:aisha /home/aisha/aishacrm

  # Clone your repo (replace with your actual repo URL or inject later)
  - sudo -u aisha git clone https://github.com/andreibyf/aishacrm-2.git /home/aisha/aishacrm || true
  - cd /home/aisha/aishacrm/backend && sudo -u aisha npm install || true

  # Place placeholder .env (you must edit this file with actual secrets)
  - cat > /home/aisha/aishacrm/backend/.env <<'EOF'
  PORT=3001
  NODE_ENV=production
  DATABASE_URL=postgresql://postgres:changeme@db-host:5432/postgres
  ALLOWED_ORIGINS=https://your-frontend.example
EOF
  - chown aisha:aisha /home/aisha/aishacrm/backend/.env
  - chmod 600 /home/aisha/aishacrm/backend/.env

  # Run migrations and seed as aisha user
  - cd /home/aisha/aishacrm/backend && sudo -u aisha node scripts/run_migrations.js || true
  - cd /home/aisha/aishacrm/backend && sudo -u aisha npm run seed || true

  # Create systemd service
  - cat > /etc/systemd/system/aisha.service <<'EOF'
[Unit]
Description=Aisha CRM Backend
After=network.target

[Service]
Type=simple
User=aisha
WorkingDirectory=/home/aisha/aishacrm/backend
ExecStart=/usr/bin/node server.js
Restart=on-failure
Environment=NODE_ENV=production
Environment=PORT=3001

[Install]
WantedBy=multi-user.target
EOF
  - systemctl daemon-reload
  - systemctl enable --now aisha.service || true

  # Nginx site (simple reverse proxy)
  - cat > /etc/nginx/sites-available/aisha <<'EOF'
server {
  listen 80;
  server_name _;

  location / {
    proxy_pass http://127.0.0.1:3001;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
  }
}
EOF
  - ln -sf /etc/nginx/sites-available/aisha /etc/nginx/sites-enabled/aisha
  - systemctl restart nginx || true

final_message: "Aisha backend bootstrap completed. Edit /home/aisha/aishacrm/backend/.env with production DATABASE_URL and secrets."
