export {
  ADAPTER_CAPABILITIES,
  ADAPTER_LIFECYCLE_STATES,
  REQUIRED_ADAPTER_METHODS,
  assertAdapterConformsToContract,
  getAdapterCapabilities,
  validateFetchResult,
  validateInboundMessage,
  validateAckResult,
  validateSendResult,
  validateNormalizedError,
  validateHealthResult,
} from './providerAdapterContract.js';

export {
  CURSOR_STRATEGIES,
  DEFAULT_RAW_RETENTION_DAYS,
  MIN_RAW_RETENTION_DAYS,
  MAX_RAW_RETENTION_DAYS,
  validateSyncCursor,
  validateSyncState,
  validateRetentionPolicy,
  buildDefaultSyncState,
  buildRetentionPolicy,
  isWithinReplayWindow,
} from './syncStateContract.js';

export {
  SAFETY_VERDICTS,
  THREAT_CATEGORIES,
  AUTH_RESULT_TYPES,
  AUTH_RESULT_VALUES,
  validateSafetyClassification,
  validateAuthResult,
  buildDefaultSafetyClassification,
  classifyFromHeaders,
  parseSpamScore,
  parseAuthenticationResults,
} from './inboundSafetyContract.js';

export {
  EMAIL_TONE,
  EMAIL_LENGTH_TIER,
  GUARDRAIL_SEVERITY,
  LENGTH_LIMITS,
  buildDefaultGuardrails,
  validateGuardrailsConfig,
  evaluateDraft,
  buildStyleDirective,
  countWords,
} from './emailStyleGuardrailsContract.js';

export {
  RETRY_STRATEGY,
  DELIVERY_STATUS,
  ERROR_CATEGORY,
  AUDIT_EVENT_TYPE,
  DEFAULT_MAX_RETRIES,
  DEFAULT_INITIAL_BACKOFF_SECONDS,
  DEFAULT_MAX_BACKOFF_SECONDS,
  buildRetryConfig,
  buildDeliveryState,
  buildAuditEvent,
  buildDeliveryAttempt,
  validateRetryConfig,
  validateDeliveryState,
  validateAuditEvent,
  classifyErrorCategory,
  shouldRetry,
  calculateBackoffSeconds,
  calculateNextRetryAt,
  parseRetryAfterHeader,
  applyDeliverySuccess,
  applyDeliveryFailure,
  appendAuditEvent,
  summarizeDeliveryState,
} from './inboundDeliveryRetryContract.js';
