#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Fail on first error
set -e

# Run lint to catch syntax errors
npm run lint -- --max-warnings 0

# Run build to catch compile errors
npm run build
